/** Blueprint 6.4: a fixed vocabulary keeps the audit log queryable. */
export const AUDIT_ACTIONS = {
  MESS_CREATE: 'MESS_CREATE',
  MESS_UPDATE: 'MESS_UPDATE',

  INVITATION_CREATE: 'INVITATION_CREATE',
  INVITATION_REVOKE: 'INVITATION_REVOKE',
  MEMBERSHIP_JOIN: 'MEMBERSHIP_JOIN',
  MEMBERSHIP_ROLE_UPDATE: 'MEMBERSHIP_ROLE_UPDATE',
  MEMBERSHIP_STATUS_UPDATE: 'MEMBERSHIP_STATUS_UPDATE',
  OWNERSHIP_TRANSFER: 'OWNERSHIP_TRANSFER',

  MEAL_OVERRIDE: 'MEAL_OVERRIDE',

  EXPENSE_CREATE: 'EXPENSE_CREATE',
  EXPENSE_UPDATE: 'EXPENSE_UPDATE',
  EXPENSE_VOID: 'EXPENSE_VOID',

  DEPOSIT_CREATE: 'DEPOSIT_CREATE',
  DEPOSIT_UPDATE: 'DEPOSIT_UPDATE',
  DEPOSIT_VOID: 'DEPOSIT_VOID',

  PERIOD_CREATE: 'PERIOD_CREATE',
  PERIOD_CLOSE: 'PERIOD_CLOSE',
  PERIOD_REOPEN: 'PERIOD_REOPEN',

  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ENTITIES = {
  MESS: 'Mess',
  MEMBERSHIP: 'Membership',
  INVITATION: 'Invitation',
  MEAL_ENTRY: 'MealEntry',
  EXPENSE: 'Expense',
  DEPOSIT: 'Deposit',
  MESS_PERIOD: 'MessPeriod',
  USER: 'User',
} as const;

export type AuditEntity = (typeof AUDIT_ENTITIES)[keyof typeof AUDIT_ENTITIES];
